### ISSUE TITLE
Spam Open Box say that when i use it

### ISSUE THREAD

**Issue by leowo0k** [kixxzy/blooket-hack#367]
VM269:1          GET https://api.blooket.com/api/games?gameId=628bf0a5f13fa30455b33c60 404 (Not Found)
FvgfW @ VM269:1
(anonymous) @ VM269:1
(anonymous) @ VM269:1
VM272:1 Uncaught (in promise) SyntaxError: Unexpected token o in JSON at position 1
await (async)
(anonymous) @ VM269:1

**Comment by hecker1834** [comment]
Same

**Comment by kixxzy** [comment]
fixed
